---
- name: Running something
  hosts: routers
  gather_facts: False
  connection: local
  tasks:
   - name: My Task
     ios_command:
         commands: show int des
     register: output
   - name: Display task
     debug:
       var: output
